Parameters:
  KeyName:
    Description: Name of an existing keypair you have created.
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:
  PuppetMasterEC2:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Init:
        configSets:
          InstallAndRun:
          - Configure        
        Configure:
          commands:
            01-test:
              command: !Sub |
                echo "hello init" > /tmp/hello.txt
            02-configure:
              command: !Sub |
                sudo rpm -Uvh https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
            03-install:
              command: !Sub |
                yum install -y puppetserver nano git
    Properties:
      SecurityGroups:
      - !Ref InstanceSecurityGroup    
      Tags:
        - 
          Key: "Name"
          Value: "PuppetMaster"
      ImageId: ami-01f7527546b557442
      InstanceType: t2.micro
      KeyName: !Ref 'KeyName'
      UserData:
        "Fn::Base64":
          !Sub |
             #!/bin/bash
             sudo yum install -y aws-cfn-bootstrap
             sudo /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} \
             --resource PuppetMasterEC2 --configsets InstallAndRun \
             --region ${AWS::Region}      
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
        GroupDescription: Base Security Group
        SecurityGroupIngress:
          - IpProtocol: tcp
            CidrIp: 0.0.0.0/0
            FromPort: 22
            ToPort: 22              
